project:
  type: website

website:
  title: "Michael L. Davies"
  navbar:
    background: "#dbdbdb"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MLDavies/
      - icon: twitter
        href: https://twitter.com/Michael82719108
format:
  html:
    theme: ember.scss
    css: styles.css

editor: visual

