project:
  type: website

website:
  title: "Michael L. Davies"
  navbar:
    #background: "#2C3E50"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MLDavies/
      - icon: twitter
        href: https://twitter.com/Michael82719108
format:
  html:
    theme: flatly  # ember.scss
    css: styles.css

editor: visual

comments:
  giscus:
    repo: MLDavies/data-blog